# 2.1 Data Manipulation

- 작업하기전 데이터를 저장하고 가공해야함
- 데이터를 다룰때 중요한 작업 두 가지
  1. 데이터 수집
  2. 저장된 데이터 처리
- 현대 딥러닝 프레임워크들은 Numpy의 ndarray와 유사한 tensor를 사용함
- tensor class 특징
  1. 자동 미분을 지원함
  2. 수치 연산에 GPU 가속을 사용함

## 2.1.1 Getting Started

In [2]:
from encodings.rot_13 import rot13

import torch

### Tensor
- tensor: 숫자 값의 배열
- 1차원인 경우 vector라 부름
- 2차원인 경우 matrix라 부름
- 2차원 초과의 축이 있는 경우 n차 텐서라 부름

### torch.arange
- 균일하게 분포된 값의 벡터를 생성
- 기본 step 사이즈는 1
- 지정하지 않을 시, 새로운 텐서는 주 메모리에 저장되고 CPU 기반 계산을 위해 지정됨
- 각 값들은 텐서의 요소라고 부름

In [16]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

- numel 메서드를 통해 텐서의 총 요소 개수를 확인할수 있음

In [17]:
x.numel()

12

- 텐서의 shape는 shape 속성을 통해 접근할수 있음

In [18]:
x.shape

torch.Size([12])

- 텐서의 shape를 reshape 를 호출함으로써 변경할수 있음

In [19]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

- 모든 shpae의 컴포넌트를 지정하는 것은 반복되므로 tensor의 사이즈를 안다면 한개의 컴포넌트가 주어지면 나머지를 계산할 수 있음

In [21]:
X = x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
X = x.reshape(3, -1)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

### torch.zeros & torch.ones
- shape를 지정하여 모든 요소가 0 또는 1인 텐서를 생성할수 있음

In [25]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [26]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### torch.randn
- 주어진 확률 분포에서 요소를 무작위 샘플링할 수 있음
- 기본 확률 분포는 가우시안 분포임

In [27]:
torch.randn(3, 4)

tensor([[ 0.0984,  1.2275, -0.8273,  0.2185],
        [-0.1241,  0.7186, -1.3228,  1.2757],
        [-0.5779, -0.1083,  0.6367, -0.1744]])

### torch.tensor
- python 리스트를 제공함으로써 tensor를 생성할 수 있음

In [31]:
torch.tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 2.1.2 Indexing and Slicing

In [32]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [34]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.3 Operations

단항 스칼라 연산자 예시
- $ e^x $

In [39]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

이진 스칼라 연산자 예시

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y

torch.concat
- tensor 리스트와 축을 지정하여 tensor 를 합칠수 있음

In [42]:
X=torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y=torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y), dim=0), torch.cat((X, Y), dim=1),

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

논리 연산자를 통해 이진 텐서를 구성할수 있음

In [43]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

전체 tensor의 합을 구할수 있음

In [44]:
X.sum()

tensor(66.)

## 2.1.4 Broadcasting
- 특정 조건 하에서 shape이 다르더라고 boradcating 메커니즘을 호출하여 요소별 이항 연상을 수행할수 있음
- Broadcasting 이 수행하는 2개의 프로시저
  1. 길이가 1인 축을 따라 요소를 복사하여 두 배열을 확장 -> 두 텐서가 동일한 모양 갖도록 함
  2. 결과 배열에 대해 요소별 연산 수행

In [46]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [47]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.5 Saving Memory

In [48]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [50]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
id(Z): 4486786224
id(Z): 4486786224


In [51]:
before = id(X)
X += Y
id(X) == before

True

## 2.1.6 Conversion to Other Python Objects
- PyTorch -> NumPy tensor 변환과 그 반대 변환 가능
- torch tensor와 numpy array 는 기본 메모리를 공유함 -> in-place 연산을 통해 한개를 변환하면 나머지도 변함

In [53]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

- size-1 tensor를 python 스칼라로 바꾸려면 item 함수를 호출 하거나 python 내장 함수를 사용할수 있음

In [56]:
a=torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# Exercise

## 1.

In [63]:
X < Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [64]:
X > Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [65]:
X == Y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

2.

In [74]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(3).reshape((1, 3))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2]]))

In [75]:
a + b

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

In [79]:
e = torch.arange(12).reshape(2, -1, 6)
f = torch.tensor([1, 2, 3, 4]).reshape(-1, 4, 1)
e, f, e.shape, f.shape

(tensor([[[ 0,  1,  2,  3,  4,  5]],
 
         [[ 6,  7,  8,  9, 10, 11]]]),
 tensor([[[1],
          [2],
          [3],
          [4]]]),
 torch.Size([2, 1, 6]),
 torch.Size([1, 4, 1]))

In [80]:
e+f

tensor([[[ 1,  2,  3,  4,  5,  6],
         [ 2,  3,  4,  5,  6,  7],
         [ 3,  4,  5,  6,  7,  8],
         [ 4,  5,  6,  7,  8,  9]],

        [[ 7,  8,  9, 10, 11, 12],
         [ 8,  9, 10, 11, 12, 13],
         [ 9, 10, 11, 12, 13, 14],
         [10, 11, 12, 13, 14, 15]]])